# Generated by Django 4.2.3 on 2023-08-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_items',
            name='item_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
