# Generated by Django 4.2.3 on 2023-08-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_base_order_is_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base_order',
            old_name='discount',
            new_name='total',
        ),
    ]
