# Generated by Django 4.2.3 on 2023-08-12 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_base_order_is_approved_delete_base_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_Discussios',
            fields=[
                ('discussion_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.base_issue')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
