# Generated by Django 4.2.3 on 2023-08-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_is_done_base_order_is_delivered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base_discussios',
            old_name='description',
            new_name='comment',
        ),
    ]
