# Generated by Django 4.2.3 on 2023-08-12 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_description_base_discussios_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Base_Discussios',
            new_name='Base_Discussions',
        ),
    ]
