# Generated by Django 4.2.3 on 2023-09-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_base_discussios_base_discussions'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_issue',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
