# Generated by Django 4.2.3 on 2023-09-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_base_issue_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_user',
            name='pincode',
            field=models.CharField(default='', max_length=255),
        ),
    ]
