# Generated by Django 4.2.3 on 2023-09-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_base_donations_donator_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_order',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
