# Generated by Django 4.2.3 on 2023-09-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_base_order_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_order',
            name='delivered_date',
            field=models.DateTimeField(default=None),
        ),
    ]
