# Generated by Django 4.2.3 on 2023-09-17 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_base_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_order',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.date(2023, 9, 17)),
        ),
    ]
