# Generated by Django 4.2.3 on 2023-09-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_base_order_delivered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_order',
            name='delivered_date',
            field=models.DateTimeField(default=None),
        ),
    ]
